services:
  proof-server:
    container_name: 'token-proof-server'
    image: "midnightnetwork/proof-server:4.0.0"
    command: ["midnight-proof-server --network testnet"]
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"
