name: sov-sdk-testing-docker

on:
  push:
    branches:
      - main

# Automatically cancels a job if a new commit is pushed to the same PR, branch, or tag.
# Source: <https://stackoverflow.com/a/72408109/5148606>
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-and-push:
    strategy:
      matrix:
        platform:
        - arch: arm64
          os: ubuntu-24.04-arm
        - arch: amd64
          os: ubuntu-24.04

    runs-on: ${{ matrix.platform.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false
          swap-storage: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up SSH key
        run: |
          mkdir -p ${{ runner.temp }}/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${{ runner.temp }}/.ssh/id_rsa
          chmod 600 ${{ runner.temp }}/.ssh/id_rsa

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache-${{ matrix.platform.arch }}
          key: ${{ runner.os }}-buildx-${{ matrix.platform.arch }}-${{ hashFiles('./hyperlane.Dockerfile', 'rust/**/*') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.platform.arch }}-

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./hyperlane.Dockerfile
          push: true
          # todo: tag with refs on pull requests
          tags: ghcr.io/${{ github.repository_owner }}/hyperlane:latest-${{ matrix.platform.arch }}
          ssh: default=${{ runner.temp }}/.ssh/id_rsa
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache-${{ matrix.platform.arch }}
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new
          # workaround for https://github.com/Noelware/docker-manifest-action/issues/131
          provenance: false

      # cache would grow infinitely if we just update the same artifacts,
      # intsead we create a new cache every time and overwrite existing
      # https://github.com/moby/buildkit/issues/1896
      - name: Overwrite cache
        run: |
          rm -rf "${{ runner.temp }}/.buildx-cache-${{ matrix.platform.arch }}"
          mv "${{ runner.temp }}/.buildx-cache-new" "${{ runner.temp }}/.buildx-cache-${{ matrix.platform.arch }}"

  merge-docker-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@0.4.3
        with:
          inputs: ghcr.io/${{ github.repository_owner }}/hyperlane:latest
          images: ghcr.io/${{ github.repository_owner }}/hyperlane:latest-amd64,ghcr.io/${{ github.repository_owner }}/hyperlane:latest-arm64
          push: true
